<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Adila-5.local" ignored="0" name="Default test" tests="1" failures="1" timestamp="31 May 2018 19:58:09 GMT" time="12.252" errors="0">
  <testcase name="runScenario" time="11.996" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at ticketmaster.step_definitions.Login.i_log_in_with_valid_credentials(Login.java:32)
at âœ½.I log in with valid credentials(src/test/resources/ticketmaster.features/login.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
